# ============================================================
# MANAS.AI PORTFOLIO API
# Deployment-safe version
#
# FastAPI
# SQLAlchemy
# SQLite locally / PostgreSQL live
# Lightweight TF-IDF-style RAG retrieval
# Groq generation
# JWT Admin CMS
# ============================================================

import math
import os
import re
import uuid

from collections import Counter
from typing import Dict
from typing import List

from dotenv import load_dotenv

from fastapi import Depends
from fastapi import FastAPI
from fastapi import HTTPException

from fastapi.middleware.cors import CORSMiddleware

from groq import Groq

from sqlalchemy.orm import Session


from database import Base
from database import SessionLocal
from database import engine
from database import get_db

from models import Certification
from models import Education
from models import Experience
from models import KnowledgeGap
from models import Project
from models import Skill
from models import WebsiteSettings

from schemas import AdminLogin
from schemas import CertificationCreate
from schemas import CertificationUpdate
from schemas import EducationCreate
from schemas import EducationUpdate
from schemas import ExperienceCreate
from schemas import ExperienceUpdate
from schemas import KnowledgeGapCreate
from schemas import KnowledgeGapUpdate
from schemas import ProjectCreate
from schemas import ProjectUpdate
from schemas import SkillCreate
from schemas import SkillUpdate
from schemas import WebsiteSettingsUpdate

from auth import authenticate_admin
from auth import create_access_token
from auth import require_admin

from seed_data import seed_database


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv()


GROQ_API_KEY = os.getenv(
    "GROQ_API_KEY"
)


if not GROQ_API_KEY:

    raise RuntimeError(
        "GROQ_API_KEY missing in environment."
    )


# ============================================================
# CONFIGURATION
# ============================================================

APP_NAME = (
    "Manas.AI Portfolio API"
)

APP_VERSION = "4.0.0"


GROQ_MODEL = os.getenv(

    "GROQ_MODEL",

    "openai/gpt-oss-120b"

)


DEFAULT_TOP_K = 7

MAX_TOP_K = 10


# Lightweight lexical retrieval threshold.
#
# Unlike the previous embedding cosine similarity,
# this score is generated by local TF-IDF-style retrieval.

MIN_RETRIEVAL_SCORE = 0.025


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

Base.metadata.create_all(
    bind=engine
)


seed_database()


# ============================================================
# FASTAPI
# ============================================================

app = FastAPI(

    title=APP_NAME,

    version=APP_VERSION,

    description=(
        "AI-powered recruiter portfolio for "
        "Manas Pandey with Admin CMS, "
        "JD analysis and evidence-grounded RAG."
    ),

)


# ============================================================
# CORS
# ============================================================

allowed_origins = [

    "http://127.0.0.1:5500",

    "http://localhost:5500",

    "http://127.0.0.1:3000",

    "http://localhost:3000",

    "http://127.0.0.1:5173",

    "http://localhost:5173",

    "http://127.0.0.1:8000",

    "http://localhost:8000",

]


FRONTEND_URL = os.getenv(
    "FRONTEND_URL"
)


if FRONTEND_URL:

    clean_frontend_url = (
        FRONTEND_URL.rstrip("/")
    )

    if (
        clean_frontend_url
        not in
        allowed_origins
    ):

        allowed_origins.append(
            clean_frontend_url
        )


app.add_middleware(

    CORSMiddleware,

    allow_origins=
        allowed_origins,

    allow_credentials=False,

    allow_methods=["*"],

    allow_headers=["*"],

)


# ============================================================
# GROQ CLIENT
# ============================================================

groq_client = Groq(

    api_key=
        GROQ_API_KEY

)


# ============================================================
# LIGHTWEIGHT RETRIEVAL ENGINE
# ============================================================

# No SentenceTransformer.
# No PyTorch.
# No NumPy.
#
# We maintain a TF-IDF-style index completely
# using Python standard-library objects.


STOP_WORDS = {

    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "being",
    "but",
    "by",
    "can",
    "did",
    "do",
    "does",
    "for",
    "from",
    "had",
    "has",
    "have",
    "he",
    "her",
    "his",
    "how",
    "i",
    "in",
    "into",
    "is",
    "it",
    "its",
    "me",
    "my",
    "of",
    "on",
    "or",
    "our",
    "she",
    "that",
    "the",
    "their",
    "them",
    "there",
    "these",
    "they",
    "this",
    "to",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "why",
    "with",
    "you",
    "your",
}


ai_documents = []


document_term_counts = []

document_norms = []

idf_values = {}


# ============================================================
# TOKENIZATION
# ============================================================

def normalize_token(
    token: str
):

    return (
        token
        .strip()
        .lower()
    )


def tokenize(
    text: str
):

    if not text:

        return []


    # Keeps useful technology expressions:
    #
    # fastapi
    # c++
    # c#
    # node.js
    # jwt
    # yolov8

    raw_tokens = re.findall(

        r"[a-zA-Z0-9][a-zA-Z0-9+#._/-]*",

        text.lower()

    )


    tokens = []


    for token in raw_tokens:

        token = normalize_token(
            token
        )


        if (
            len(token) <= 1
            and
            token not in {
                "c",
                "r"
            }
        ):

            continue


        if token in STOP_WORDS:

            continue


        tokens.append(
            token
        )


    return tokens


# ============================================================
# AI KNOWLEDGE GENERATION
# ============================================================

def rebuild_ai_knowledge():

    global ai_documents

    global document_term_counts

    global document_norms

    global idf_values


    db = SessionLocal()


    generated_documents = []


    try:

        # ----------------------------------------------------
        # EXPERIENCE
        # ----------------------------------------------------

        experiences = (

            db.query(
                Experience
            )

            .filter(

                Experience.is_active
                ==
                True,

                Experience.include_in_ai
                ==
                True,

            )

            .order_by(
                Experience.display_order
            )

            .all()

        )


        for item in experiences:

            generated_documents.append({

                "id":
                    f"experience_{item.id}",

                "title":
                    (
                        f"{item.role} - "
                        f"{item.company}"
                    ),

                "source":
                    "Professional Experience",

                "category":
                    "experience",

                "content":
                    (
                        f"Company: {item.company}. "
                        f"Role: {item.role}. "
                        f"Period: "
                        f"{item.start_date or ''} "
                        f"to "
                        f"{item.end_date or ''}. "
                        f"Description: "
                        f"{item.description or ''}. "
                        f"Technologies: "
                        f"{item.technologies or ''}."
                    ),

            })


        # ----------------------------------------------------
        # PROJECTS
        # ----------------------------------------------------

        projects = (

            db.query(
                Project
            )

            .filter(

                Project.is_active
                ==
                True,

                Project.include_in_ai
                ==
                True,

            )

            .order_by(
                Project.display_order
            )

            .all()

        )


        for item in projects:

            generated_documents.append({

                "id":
                    f"project_{item.id}",

                "title":
                    item.title,

                "source":
                    item.project_type,

                "category":
                    "project",

                "content":
                    (
                        f"Project: {item.title}. "
                        f"Category: "
                        f"{item.category or ''}. "
                        f"Problem and summary: "
                        f"{item.short_description or ''}. "
                        f"Implementation: "
                        f"{item.detailed_description or ''}. "
                        f"Technologies: "
                        f"{item.technologies or ''}. "
                        f"Architecture: "
                        f"{item.architecture or ''}. "
                        f"Outcome: "
                        f"{item.result or ''}."
                    ),

            })


        # ----------------------------------------------------
        # SKILLS
        # ----------------------------------------------------

        skills = (

            db.query(
                Skill
            )

            .filter(

                Skill.is_active
                ==
                True,

                Skill.include_in_ai
                ==
                True,

            )

            .order_by(
                Skill.display_order
            )

            .all()

        )


        for item in skills:

            generated_documents.append({

                "id":
                    f"skill_{item.id}",

                "title":
                    item.name,

                "source":
                    "Skills",

                "category":
                    "skills",

                "content":
                    (
                        f"Skill: {item.name}. "
                        f"Category: "
                        f"{item.category or ''}. "
                        f"Evidence level: "
                        f"{item.evidence_level or ''}. "
                        f"Description: "
                        f"{item.description or ''}."
                    ),

            })


        # ----------------------------------------------------
        # EDUCATION
        # ----------------------------------------------------

        education_items = (

            db.query(
                Education
            )

            .filter(

                Education.is_active
                ==
                True,

                Education.include_in_ai
                ==
                True,

            )

            .order_by(
                Education.display_order
            )

            .all()

        )


        for item in education_items:

            generated_documents.append({

                "id":
                    f"education_{item.id}",

                "title":
                    (
                        item.degree
                        or
                        item.institution
                    ),

                "source":
                    "Education",

                "category":
                    "education",

                "content":
                    (
                        f"Institution: "
                        f"{item.institution}. "
                        f"Degree: "
                        f"{item.degree or ''}. "
                        f"Period: "
                        f"{item.start_year or ''} "
                        f"to "
                        f"{item.end_year or ''}. "
                        f"Location: "
                        f"{item.location or ''}. "
                        f"Description: "
                        f"{item.description or ''}."
                    ),

            })


        # ----------------------------------------------------
        # CERTIFICATIONS
        # ----------------------------------------------------

        certifications = (

            db.query(
                Certification
            )

            .filter(

                Certification.is_active
                ==
                True,

                Certification.include_in_ai
                ==
                True,

            )

            .order_by(
                Certification.display_order
            )

            .all()

        )


        for item in certifications:

            generated_documents.append({

                "id":
                    f"certification_{item.id}",

                "title":
                    item.name,

                "source":
                    "Certification",

                "category":
                    "certification",

                "content":
                    (
                        f"Certification: "
                        f"{item.name}. "
                        f"Issuer: "
                        f"{item.issuer or ''}. "
                        f"Issue date: "
                        f"{item.issue_date or ''}. "
                        f"Description: "
                        f"{item.description or ''}."
                    ),

            })


        # ----------------------------------------------------
        # KNOWN GAPS
        # ----------------------------------------------------

        gaps = (

            db.query(
                KnowledgeGap
            )

            .filter(
                KnowledgeGap.is_active
                ==
                True
            )

            .all()

        )


        for item in gaps:

            generated_documents.append({

                "id":
                    f"gap_{item.id}",

                "title":
                    (
                        f"{item.topic} "
                        f"Experience"
                    ),

                "source":
                    "Known Evidence Gap",

                "category":
                    "gap",

                "content":
                    item.statement,

            })


    finally:

        db.close()


    ai_documents = (
        generated_documents
    )


    # --------------------------------------------------------
    # BUILD LIGHTWEIGHT TF-IDF INDEX
    # --------------------------------------------------------

    document_term_counts = []


    document_frequency = Counter()


    for document in ai_documents:

        searchable_text = (

            document["title"]

            +

            " "

            +

            document["category"]

            +

            " "

            +

            document["content"]

        )


        terms = tokenize(
            searchable_text
        )


        counts = Counter(
            terms
        )


        document_term_counts.append(
            counts
        )


        for term in counts.keys():

            document_frequency[
                term
            ] += 1


    document_count = max(

        len(
            ai_documents
        ),

        1

    )


    idf_values = {}


    for term, frequency in (
        document_frequency.items()
    ):

        idf_values[
            term
        ] = (

            math.log(

                (
                    document_count
                    +
                    1
                )

                /

                (
                    frequency
                    +
                    1
                )

            )

            +

            1.0

        )


    # --------------------------------------------------------
    # PRECALCULATE DOCUMENT VECTOR NORMS
    # --------------------------------------------------------

    document_norms = []


    for counts in (
        document_term_counts
    ):

        squared_sum = 0.0


        for term, frequency in (
            counts.items()
        ):

            weight = (

                (
                    1.0
                    +
                    math.log(
                        frequency
                    )
                )

                *

                idf_values.get(
                    term,
                    1.0
                )

            )


            squared_sum += (
                weight
                *
                weight
            )


        document_norms.append(

            math.sqrt(
                squared_sum
            )

            or

            1.0

        )


    print(

        f"AI knowledge rebuilt: "
        f"{len(ai_documents)} chunks"

    )


# ============================================================
# INITIAL INDEX BUILD
# ============================================================

rebuild_ai_knowledge()


# ============================================================
# LIGHTWEIGHT RETRIEVAL
# ============================================================

def retrieve_context(

    query: str,

    top_k: int = DEFAULT_TOP_K

):

    if not ai_documents:

        return []


    query_terms = tokenize(
        query
    )


    if not query_terms:

        return []


    query_counts = Counter(
        query_terms
    )


    query_weights = {}


    query_norm_squared = 0.0


    for term, frequency in (
        query_counts.items()
    ):

        weight = (

            (
                1.0
                +
                math.log(
                    frequency
                )
            )

            *

            idf_values.get(
                term,
                1.8
            )

        )


        query_weights[
            term
        ] = weight


        query_norm_squared += (
            weight
            *
            weight
        )


    query_norm = (

        math.sqrt(
            query_norm_squared
        )

        or

        1.0

    )


    results = []


    normalized_query = (
        query.lower().strip()
    )


    for index, document in enumerate(
        ai_documents
    ):

        counts = (
            document_term_counts[
                index
            ]
        )


        dot_product = 0.0


        matched_terms = 0


        for term, query_weight in (
            query_weights.items()
        ):

            frequency = counts.get(
                term,
                0
            )


            if frequency <= 0:

                continue


            matched_terms += 1


            document_weight = (

                (
                    1.0
                    +
                    math.log(
                        frequency
                    )
                )

                *

                idf_values.get(
                    term,
                    1.0
                )

            )


            dot_product += (

                query_weight

                *

                document_weight

            )


        score = (

            dot_product

            /

            (
                query_norm
                *
                document_norms[index]
            )

        )


        # ----------------------------------------------------
        # SMALL EXACT-MATCH BOOST
        # ----------------------------------------------------

        searchable = (

            document["title"]

            +

            " "

            +

            document["content"]

        ).lower()


        # Exact query phrase.
        if (
            normalized_query
            and
            normalized_query
            in
            searchable
        ):

            score += 0.20


        # Technology-token coverage.
        if query_terms:

            coverage = (

                matched_terms

                /

                len(
                    set(
                        query_terms
                    )
                )

            )


            score += (
                coverage
                *
                0.08
            )


        result = dict(
            document
        )


        result[
            "similarity"
        ] = float(
            score
        )


        results.append(
            result
        )


    results.sort(

        key=lambda item:
            item["similarity"],

        reverse=True

    )


    return results[
        :top_k
    ]


# ============================================================
# CONTEXT BUILDER
# ============================================================

def build_context(
    documents
):

    blocks = []


    for number, item in enumerate(

        documents,

        start=1

    ):

        blocks.append(

            f"""
EVIDENCE {number}

Title:
{item["title"]}

Source:
{item["source"]}

Category:
{item["category"]}

Content:
{item["content"]}
""".strip()

        )


    return "\n\n---\n\n".join(
        blocks
    )


# ============================================================
# CHAT MEMORY
# ============================================================

conversation_memory: Dict[
    str,
    List[dict]
] = {}


MAX_MEMORY_MESSAGES = 8


# ============================================================
# ROOT
# ============================================================

@app.get("/")

def root():

    return {

        "application":
            APP_NAME,

        "version":
            APP_VERSION,

        "status":
            "running",

        "retrieval_engine":
            "lightweight-tfidf",

        "ai_chunks":
            len(ai_documents),

        "docs":
            "/docs",

        "chat":
            "/api/chat",

        "jd_analyzer":
            "/api/jd/analyze",

        "admin_login":
            "/api/admin/login",

    }


# ============================================================
# HEALTH
# ============================================================

@app.get("/health")

def health():

    return {

        "status":
            "healthy",

        "model":
            GROQ_MODEL,

        "retrieval_engine":
            "lightweight-tfidf",

        "ai_chunks":
            len(ai_documents),

    }


# ============================================================
# DEBUG RETRIEVAL
# ============================================================

@app.get(
    "/api/search"
)

def debug_search(

    q: str,

    top_k: int = 5

):

    safe_top_k = min(

        max(
            top_k,
            2
        ),

        MAX_TOP_K

    )


    documents = retrieve_context(

        q,

        safe_top_k

    )


    return {

        "query":
            q,

        "results":
            [

                {

                    "id":
                        item["id"],

                    "title":
                        item["title"],

                    "source":
                        item["source"],

                    "category":
                        item["category"],

                    "score":
                        round(
                            item["similarity"],
                            4
                        ),

                }

                for item in documents

            ],

    }


# ============================================================
# PUBLIC API
# ============================================================

@app.get(
    "/api/public/settings"
)

def public_settings(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            WebsiteSettings
        )

        .first()

    )


@app.get(
    "/api/public/experience"
)

def public_experience(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            Experience
        )

        .filter(
            Experience.is_active
            ==
            True
        )

        .order_by(
            Experience.display_order
        )

        .all()

    )


@app.get(
    "/api/public/projects"
)

def public_projects(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            Project
        )

        .filter(
            Project.is_active
            ==
            True
        )

        .order_by(
            Project.display_order
        )

        .all()

    )


@app.get(
    "/api/public/skills"
)

def public_skills(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            Skill
        )

        .filter(
            Skill.is_active
            ==
            True
        )

        .order_by(
            Skill.display_order
        )

        .all()

    )


@app.get(
    "/api/public/education"
)

def public_education(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            Education
        )

        .filter(
            Education.is_active
            ==
            True
        )

        .order_by(
            Education.display_order
        )

        .all()

    )


@app.get(
    "/api/public/certifications"
)

def public_certifications(

    db: Session = Depends(
        get_db
    )

):

    return (

        db.query(
            Certification
        )

        .filter(
            Certification.is_active
            ==
            True
        )

        .order_by(
            Certification.display_order
        )

        .all()

    )


# ============================================================
# ADMIN LOGIN
# ============================================================

@app.post(
    "/api/admin/login"
)

def admin_login(
    payload: AdminLogin
):

    authenticated = (

        authenticate_admin(

            payload.email,

            payload.password

        )

    )


    if not authenticated:

        raise HTTPException(

            status_code=401,

            detail=(
                "Invalid email or password"
            ),

        )


    token = create_access_token(
        payload.email
    )


    return {

        "access_token":
            token,

        "token_type":
            "bearer",

    }


# ============================================================
# ADMIN DASHBOARD
# ============================================================

@app.get(
    "/api/admin/dashboard"
)

def admin_dashboard(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return {

        "projects":
            db.query(
                Project
            ).count(),

        "experience":
            db.query(
                Experience
            ).count(),

        "skills":
            db.query(
                Skill
            ).count(),

        "education":
            db.query(
                Education
            ).count(),

        "certifications":
            db.query(
                Certification
            ).count(),

        "knowledge_gaps":
            db.query(
                KnowledgeGap
            ).count(),

        "ai_chunks":
            len(ai_documents),

        "admin":
            admin,

    }


# ============================================================
# ADMIN SETTINGS
# ============================================================

@app.get(
    "/api/admin/settings"
)

def get_admin_settings(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            WebsiteSettings
        )

        .first()

    )


@app.put(
    "/api/admin/settings"
)

def update_admin_settings(

    payload:
        WebsiteSettingsUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = (

        db.query(
            WebsiteSettings
        )

        .first()

    )


    if not item:

        item = WebsiteSettings()

        db.add(
            item
        )


    updates = payload.model_dump(
        exclude_unset=True
    )


    for field, value in (
        updates.items()
    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    return item


# ============================================================
# EXPERIENCE CRUD
# ============================================================

@app.get(
    "/api/admin/experience"
)

def admin_experience(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            Experience
        )

        .order_by(
            Experience.display_order
        )

        .all()

    )


@app.post(
    "/api/admin/experience"
)

def create_experience(

    payload:
        ExperienceCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = Experience(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/experience/{item_id}"
)

def update_experience(

    item_id: int,

    payload:
        ExperienceUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Experience,
        item_id
    )


    if not item:

        raise HTTPException(

            status_code=404,

            detail=(
                "Experience not found"
            ),

        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/experience/{item_id}"
)

def delete_experience(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Experience,
        item_id
    )


    if not item:

        raise HTTPException(

            status_code=404,

            detail=(
                "Experience not found"
            ),

        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# PROJECT CRUD
# ============================================================

@app.get(
    "/api/admin/projects"
)

def admin_projects(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            Project
        )

        .order_by(
            Project.display_order
        )

        .all()

    )


@app.post(
    "/api/admin/projects"
)

def create_project(

    payload:
        ProjectCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = Project(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/projects/{item_id}"
)

def update_project(

    item_id: int,

    payload:
        ProjectUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Project,
        item_id
    )


    if not item:

        raise HTTPException(

            status_code=404,

            detail=(
                "Project not found"
            ),

        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/projects/{item_id}"
)

def delete_project(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Project,
        item_id
    )


    if not item:

        raise HTTPException(

            status_code=404,

            detail=(
                "Project not found"
            ),

        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# SKILL CRUD
# ============================================================

@app.get(
    "/api/admin/skills"
)

def admin_skills(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            Skill
        )

        .order_by(
            Skill.display_order
        )

        .all()

    )


@app.post(
    "/api/admin/skills"
)

def create_skill(

    payload:
        SkillCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = Skill(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/skills/{item_id}"
)

def update_skill(

    item_id: int,

    payload:
        SkillUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Skill,
        item_id
    )


    if not item:

        raise HTTPException(

            status_code=404,

            detail="Skill not found",

        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/skills/{item_id}"
)

def delete_skill(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Skill,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Skill not found"
        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# EDUCATION CRUD
# ============================================================

@app.get(
    "/api/admin/education"
)

def admin_education(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            Education
        )

        .order_by(
            Education.display_order
        )

        .all()

    )


@app.post(
    "/api/admin/education"
)

def create_education(

    payload:
        EducationCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = Education(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/education/{item_id}"
)

def update_education(

    item_id: int,

    payload:
        EducationUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Education,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Education not found"
        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/education/{item_id}"
)

def delete_education(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Education,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Education not found"
        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# CERTIFICATION CRUD
# ============================================================

@app.get(
    "/api/admin/certifications"
)

def admin_certifications(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            Certification
        )

        .order_by(
            Certification.display_order
        )

        .all()

    )


@app.post(
    "/api/admin/certifications"
)

def create_certification(

    payload:
        CertificationCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = Certification(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/certifications/{item_id}"
)

def update_certification(

    item_id: int,

    payload:
        CertificationUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Certification,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Certification not found"
        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/certifications/{item_id}"
)

def delete_certification(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        Certification,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Certification not found"
        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# KNOWN GAP CRUD
# ============================================================

@app.get(
    "/api/admin/gaps"
)

def admin_gaps(

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    return (

        db.query(
            KnowledgeGap
        )

        .all()

    )


@app.post(
    "/api/admin/gaps"
)

def create_gap(

    payload:
        KnowledgeGapCreate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = KnowledgeGap(
        **payload.model_dump()
    )


    db.add(
        item
    )

    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.put(
    "/api/admin/gaps/{item_id}"
)

def update_gap(

    item_id: int,

    payload:
        KnowledgeGapUpdate,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        KnowledgeGap,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Gap not found"
        )


    for field, value in (

        payload
        .model_dump(
            exclude_unset=True
        )
        .items()

    ):

        setattr(
            item,
            field,
            value
        )


    db.commit()

    db.refresh(
        item
    )


    rebuild_ai_knowledge()


    return item


@app.delete(
    "/api/admin/gaps/{item_id}"
)

def delete_gap(

    item_id: int,

    db: Session = Depends(
        get_db
    ),

    admin: str = Depends(
        require_admin
    ),

):

    item = db.get(
        KnowledgeGap,
        item_id
    )


    if not item:

        raise HTTPException(
            404,
            "Gap not found"
        )


    db.delete(
        item
    )

    db.commit()


    rebuild_ai_knowledge()


    return {
        "status":
            "deleted"
    }


# ============================================================
# MANUAL AI REBUILD
# ============================================================

@app.post(
    "/api/admin/rebuild-ai"
)

def manual_rebuild(

    admin: str = Depends(
        require_admin
    )

):

    rebuild_ai_knowledge()


    return {

        "status":
            "rebuilt",

        "chunks":
            len(ai_documents),

    }


# ============================================================
# CHAT SYSTEM PROMPT
# ============================================================

CHAT_SYSTEM_PROMPT = """
You are Manas AI.

You are an evidence-grounded recruiter copilot for
software developer Manas Pandey.

You MUST answer using only the supplied evidence.

Never invent:
- employers
- clients
- professional experience
- technologies
- project outcomes
- certifications
- responsibilities
- metrics
- years of experience.

Clearly distinguish:

1. Professional Experience
2. Resume-backed Projects
3. Portfolio / Personal Projects
4. Skills

A skill entry alone does NOT prove professional
production experience.

If the supplied evidence does not support a claim,
say:

"I don't have verified evidence for that."

Keep normal recruiter answers concise,
approximately 100-220 words.

When appropriate use:

Direct Answer

Evidence

Hiring Interpretation

Visible Gap

Be balanced and evidence-grounded.
Recruiter trust is more important than exaggeration.
"""


# ============================================================
# RAG CHAT
# ============================================================

@app.post(
    "/api/chat"
)

def chat(
    payload: dict
):

    question = str(

        payload.get(
            "question",
            ""
        )

    ).strip()


    if len(question) < 2:

        raise HTTPException(

            status_code=422,

            detail=(
                "Question is required."
            ),

        )


    try:

        top_k = int(

            payload.get(
                "top_k",
                DEFAULT_TOP_K
            )

        )

    except Exception:

        top_k = (
            DEFAULT_TOP_K
        )


    top_k = min(

        max(
            top_k,
            2
        ),

        MAX_TOP_K

    )


    session_id = (

        payload.get(
            "session_id"
        )

        or

        str(
            uuid.uuid4()
        )

    )


    history = conversation_memory.get(

        session_id,

        []

    )


    retrieval_query = (
        question
    )


    # --------------------------------------------------------
    # FOLLOW-UP CONTEXT
    # --------------------------------------------------------

    if history:

        recent_questions = [

            item["content"]

            for item in history

            if item["role"]
            ==
            "user"

        ][-2:]


        if recent_questions:

            retrieval_query = (

                " ".join(
                    recent_questions
                )

                +

                " "

                +

                question

            )


    documents = retrieve_context(

        retrieval_query,

        top_k

    )


    # --------------------------------------------------------
    # CONFIDENCE GUARD
    # --------------------------------------------------------

    if (
        not documents
        or
        documents[0]["similarity"]
        <
        MIN_RETRIEVAL_SCORE
    ):

        answer = (
            "I don't have strong enough "
            "verified evidence in Manas's "
            "portfolio to answer that confidently. "
            "I don't want to invent experience."
        )


        conversation_memory.setdefault(
            session_id,
            []
        )


        conversation_memory[
            session_id
        ].extend([

            {
                "role":
                    "user",

                "content":
                    question,
            },

            {
                "role":
                    "assistant",

                "content":
                    answer,
            },

        ])


        return {

            "answer":
                answer,

            "grounded":
                False,

            "session_id":
                session_id,

            "sources":
                [],

        }


    evidence_context = (
        build_context(
            documents
        )
    )


    previous_history = "\n".join(

        [

            (
                f'{item["role"].upper()}: '
                f'{item["content"]}'
            )

            for item in history[-6:]

        ]

    )


    user_prompt = f"""
PREVIOUS CONVERSATION

{previous_history or "None"}


CURRENT QUESTION

{question}


VERIFIED PORTFOLIO EVIDENCE

{evidence_context}


Answer the recruiter using ONLY the verified evidence above.

Conversation history may help interpret follow-up questions,
but it is not independent evidence.
"""


    try:

        completion = (

            groq_client
            .chat
            .completions
            .create(

                model=
                    GROQ_MODEL,

                messages=[

                    {

                        "role":
                            "system",

                        "content":
                            CHAT_SYSTEM_PROMPT,

                    },

                    {

                        "role":
                            "user",

                        "content":
                            user_prompt,

                    },

                ],

                temperature=
                    0.15,

                max_tokens=
                    650,

            )

        )


        answer = (

            completion
            .choices[0]
            .message
            .content
            .strip()

        )


    except Exception as error:

        print(
            "Groq Chat Error:",
            type(error).__name__,
            str(error)
        )


        return {

            "answer":
                (
                    "The portfolio evidence retrieval "
                    "worked, but the language-model "
                    "service is temporarily unavailable."
                ),

            "grounded":
                False,

            "session_id":
                session_id,

            "sources":
                [],

        }


    conversation_memory.setdefault(
        session_id,
        []
    )


    conversation_memory[
        session_id
    ].extend([

        {

            "role":
                "user",

            "content":
                question,

        },

        {

            "role":
                "assistant",

            "content":
                answer,

        },

    ])


    conversation_memory[
        session_id
    ] = conversation_memory[
        session_id
    ][-MAX_MEMORY_MESSAGES:]


    return {

        "answer":
            answer,

        "grounded":
            True,

        "session_id":
            session_id,

        "sources":
            [

                {

                    "id":
                        item["id"],

                    "title":
                        item["title"],

                    "source":
                        item["source"],

                    "category":
                        item["category"],

                    "similarity":
                        round(
                            item["similarity"],
                            4
                        ),

                }

                for item in documents

            ],

    }


# ============================================================
# RESET CONVERSATION
# ============================================================

@app.post(
    "/api/chat/reset/{session_id}"
)

def reset_chat(
    session_id: str
):

    conversation_memory.pop(
        session_id,
        None
    )


    return {

        "status":
            "cleared",

        "session_id":
            session_id,

    }


# ============================================================
# JD ANALYZER
# ============================================================

JD_SYSTEM_PROMPT = """
You are an evidence-grounded technical recruiter.

Compare Manas Pandey against the supplied job description.

Use ONLY the supplied verified portfolio evidence.

Do not invent experience.

Return:

ROLE MATCH

Give a conservative percentage from 0 to 100.

STRONG MATCHES

List requirements with clear supporting evidence.

PARTIAL MATCHES

List requirements supported only by skills,
limited projects, or adjacent experience.

VISIBLE GAPS

List requirements with no verified evidence.

MOST RELEVANT EXPERIENCE

Professional experience only.

MOST RELEVANT PROJECTS

List up to three projects.

INTERVIEW FOCUS

Give three useful technical interview questions.

RECOMMENDATION

Choose exactly one:

Strong technical screen candidate

Potential technical screen candidate

Needs more evidence before screening

Do not inflate the score.
"""


@app.post(
    "/api/jd/analyze"
)

def analyze_jd(
    payload: dict
):

    jd = str(

        payload.get(
            "job_description",
            ""
        )

    ).strip()


    if len(jd) < 50:

        raise HTTPException(

            status_code=422,

            detail=(
                "Please provide a complete "
                "job description."
            ),

        )


    documents = retrieve_context(

        jd,

        MAX_TOP_K

    )


    evidence_context = (
        build_context(
            documents
        )
    )


    user_prompt = f"""
JOB DESCRIPTION

{jd}


VERIFIED MANAS PORTFOLIO EVIDENCE

{evidence_context}


Evaluate Manas only from this supplied evidence.
"""


    try:

        completion = (

            groq_client
            .chat
            .completions
            .create(

                model=
                    GROQ_MODEL,

                messages=[

                    {

                        "role":
                            "system",

                        "content":
                            JD_SYSTEM_PROMPT,

                    },

                    {

                        "role":
                            "user",

                        "content":
                            user_prompt,

                    },

                ],

                temperature=
                    0.10,

                max_tokens=
                    1000,

            )

        )


        analysis = (

            completion
            .choices[0]
            .message
            .content
            .strip()

        )


    except Exception as error:

        print(
            "JD Analyzer Error:",
            type(error).__name__,
            str(error)
        )


        analysis = (
            "The portfolio evidence was retrieved, "
            "but the AI analysis service is "
            "temporarily unavailable."
        )


    return {

        "analysis":
            analysis,

        "sources":
            [

                {

                    "id":
                        item["id"],

                    "title":
                        item["title"],

                    "source":
                        item["source"],

                    "category":
                        item["category"],

                    "similarity":
                        round(
                            item["similarity"],
                            4
                        ),

                }

                for item in documents

            ],

    }


# ============================================================
# DEVELOPMENT
# ============================================================

if __name__ == "__main__":

    import uvicorn


    uvicorn.run(

        "main:app",

        host=
            "127.0.0.1",

        port=
            8000,

        reload=
            True,

    )